config/routes.rb
Rails.application.routes.draw do

  get 'contacts/import'
  resources :contacts do
  	collection { post :import}
  end

  resources :contacts, only: [:index, :import, :show] do
    resources :phones, only: [:create, :index, :show, :update] 
  end

  resources :phones, only: [:create, :index, :show, :destroy, :update] 

  root to: "contacts#welcome"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
	
	has_many :phones, dependent: :destroy

	require 'csv'

	def self.import(file)
		CSV.foreach(file.path, { headers: true}) do |row|
				@contact = Contact.create! row.to_hash.except!("phone")
				@phone = Phone.new(number: row["phone"])
				@phone.contact = @contact
				@phone.save
			end
  end
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :contact
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def welcome
  end 

  def index
    contacts = Contact.order created_at: :desc
    render json: contacts
  end

  def show
    @contact = Contact.find params[:id]
    render json: @contact
  end

  def import

    if params[:file] 
        Contact.import(params[:file]) 
        redirect_to'http://localhost:3434', notice: "Activity Data imported!"
  	else
  		redirect_to root_url, notice: "Please upload a CSV file"
  	end
  end

  
  
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  before_action :find_phone, only: [:show, :update, :destroy]

  def create
    @contact = Contact.find(params[:contact_id])
    @phone = Phone.new(phone_params)
    @phone.contact = @contact

    if @phone.save
      render json: {id: @phone.id}
    else
      render json: { errors: @phone.errors.full_messages }      
    end
  end

  def update
    if @phone.update(phone_params)
      render json: @phone
    else
      render json: { errors: @phone.errors }
    end
  end
   
  def show 
    render json: @phone
  end

  def index
    phones = Phone.order created_at: :desc
    render json: phones
  end
  
  def destroy
    @phone.destroy
    render json: {status: 200}
  end

  private
  def phone_params
    params.permit(:id, :number, :type)
  end

  def find_phone
    @phone = Phone.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by email: params[:email]
    if user&.authenticate params[:password]
      session[:user_id] = user.id
      render json: { id: user.id }
    else
      render json: { status:401 }
    end
  end

  def destroy
    session[:user_id] = nil
    render json: { status:200 }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :update, :destroy]
  before_action :authenticate_user!, except: [:create]
  
  def current
    render json: current_user
  end
  
  def create
    new_parms = user_params
    new_parms[:password] = params[:password]
    new_parms[:password_confirmation] = params[:password_confirmation]
    @user = User.create new_parms
    if @user.save
      session[:user_id] = @user.id
      render json: @user
    else
      render json: { errors: @user.errors.full_messages }
    end
  end
  
  def show
    render json: @user
  end
  
  def update
    if @user.update(user_params)
      render json: @user
    else
      render json: { errors: @user.errors.full_messages }
    end
  end
  
  def destroy
    @user.destroy
    render json: {status: 200}
  end
  
  private
    def user_params
      params.permit(
        :user_name, :full_name, :email, :password, :password_confirmation
      )
    end
  
    def find_user
      @user = User.find(params[:id])
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/import.html.erb
<%= flash[:notice] %>
<table>
	<thead>
		<th>First Name</th>
		<th>Last Name</th>
		<th>Email</th>
		<th>Address</th>
		<th>City</th>
    <th>Province</th>
    <th>Country_name</th>
    <th>Postcode</th>
    <th>Date_added</th>
    <th>How_did_you_hear_about_us</th>
    <th>What_is_your_budget</th>
    <th>What_is_your_favourite_color</th>
     
	</thead>
	<tbody>
		<% @contacts.each do |contact| %>
			<tr>
				<td><%= contact.first_name %></td>
				<td><%= contact.last_name %></td>
				<td><%= contact.email %></td>
        <td><%= contact.address_line_1 %></td>
        <td><%= contact.city %></td>
        <td><%= contact.province %></td>
        <td><%= contact.country_name %></td>
        <td><%= contact.postcode %></td>
        <td><%= contact.date_added %></td>
        <td><%= contact.how_did_you_hear_about_us %></td>
        <td><%= contact.what_is_your_budget %></td>
        <td><%= contact.what_is_your_favourite_color %></td>
			</tr>
		<% end %>
	</tbody>
</table>
<div>
	<h4> Import that data! </h4>
		<%= form_tag import_contacts_path, multipart: true do %>
		<%= file_field_tag :file %>
		<%= submit_tag "Import CSV" %>
		<% end %> 
</div> 

app/views/contacts/welcome.html.erb
	<div class="alert alert-info" class="text-center"  role="alert">
				<%= flash[:notice]%>
	</div>
	<div class=" col-offset-6 centered">	
		<h2>Upload your file</h2> 
				<%= form_tag import_contacts_path, multipart: true do %>
				<%= file_field_tag :file %> <br/>
				<br/>
				<%= submit_tag "Import CSV", class: 'btn btn-primary mb-2' %>
				<% end %> 
		</div> 
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contacts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
   <nav class="NavBar">
      <div class="plate">
        <p class="script">
          <span>Open your CSV file</span>
        </p>
      </div>
      <div>

      </div>
    </nav>
    <%= yield %>
  </body>
</html>